INCLUDE ../../Globals/Globals.ink
INCLUDE A5_S4_D1.ink
INCLUDE A5_S4_D2.ink
INCLUDE A5_S4_D3.ink
INCLUDE A5_S4_D4.ink
INCLUDE A5_S4_D5.ink
INCLUDE A5_S4_Q1_COMPLETED.ink
INCLUDE A5_S4_Q1_ONGOING.ink
INCLUDE A5_S4_Q2_COMPLETED.ink
INCLUDE A5_S4_Q2_ONGOING.ink
// Variable Setup
CONST DIALOGUE_1 = "A5_S4_D1"
CONST DIALOGUE_2 = "A5_S4_D2"
CONST DIALOGUE_3 = "A5_S4_D3"
CONST DIALOGUE_4 = "A5_S4_D4"
CONST DIALOGUE_5 = "A5_S4_D5"
CONST QUEST_1 = "A5_S4_Q1_COMPLETED"
CONST QUEST_2 = "A5_S4_Q1_ONGOING"
CONST QUEST_3 = "A5_S4_Q2_COMPLETED"
CONST QUEST_4 = "A5_S4_Q2_ONGOING"
{
	- dialogue_id == DIALOGUE_1:
		-> A5_S4_D1
	- dialogue_id == DIALOGUE_2:
		-> A5_S4_D2
	- dialogue_id == DIALOGUE_3:
		-> A5_S4_D3
	- dialogue_id == DIALOGUE_4:
		-> A5_S4_D4
	- dialogue_id == DIALOGUE_5:
		-> A5_S4_D5
}
===A5_S4_Q1===
{
	- quest_state == "ONGOING":
		-> A5_S4_Q1_ONGOING
	- quest_state == "COMPLETED":
		-> A5_S4_Q1_COMPLETED
}
===A5_S4_Q2===
{
	- quest_state == "ONGOING":
		-> A5_S4_Q2_ONGOING
	- quest_state == "COMPLETED":
		-> A5_S4_Q2_COMPLETED
}
